### ISSUE TITLE
HyperLinks from the Entities Page are Broken

### ISSUE THREAD

**Issue by drj826** [drj826/semlang#10]
Entity ID links on the "entities.html" page should take the user to the entity in whichever document it appears.  For instance, clicking on the "rq-000005" link should take the user to that requirement in the requirements document.

The links are broken simply because there's a directory missing (the applicable document directory) in the link URL.

**Comment by drj826** [comment]
Just committed fix.

**Comment by dgpicke** [comment]
no comment - just observing.  :)

**Comment by drj826** [comment]
Thanks for observing!!
